import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by Firebase CLI

// Screens
import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';
import 'screens/reset_password_screen.dart';
import 'screens/client_dashboard_screen.dart';
import 'screens/architects_screen.dart';
import 'screens/projects_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/search_architects_screen.dart';
import 'screens/post_project_screen.dart';
import 'screens/architect_dashboard_screen.dart';

bool _isFirebaseInitialized = false;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (!_isFirebaseInitialized) {
    print('Initializing Firebase...');
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      _isFirebaseInitialized = true;
      print('Firebase initialized successfully.');
    } catch (e) {
      print('Error initializing Firebase: $e');
      // Handle the error appropriately, maybe show an error screen
    }
  } else {
    print('Firebase already initialized (via flag).');
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'HabiTect',
      theme: ThemeData(
        appBarTheme: const AppBarTheme(
          color: Colors.white,
          elevation: 0,
        ),
        colorScheme: ColorScheme.light(
          primary: const Color(0xFF6B8E23),
          secondary: const Color(0xFFE2725B),
          secondaryFixed: const Color(0xFFBDC6C2),
          tertiary: const Color(0xFFDCB287),
          tertiaryFixed: const Color(0xFF9E897B),
          tertiaryFixedDim: const Color(0xFFB5855B),
          surface: Colors.white,
          background: const Color(0xFFF9F9F7),
        ),
        fontFamily: 'Georama',
        useMaterial3: true,
        textTheme: const TextTheme(
          headlineLarge: TextStyle(
            fontSize: 24,
            fontWeight: FontWeight.w600,
            color: Colors.black87,
          ),
          bodyLarge: TextStyle(
            fontSize: 16,
            color: Colors.black54,
          ),
          labelLarge: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => SplashScreen(),
        '/login': (context) => LoginScreen(),
        '/register': (context) => RegisterScreen(),
        '/reset-password': (context) => const ResetPasswordScreen(),
        '/client-dashboard': (context) => ClientDashboard(),
        '/architects': (context) => const ArchitectsScreen(),
        '/projects': (context) => const ProjectsScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/search-architects': (context) => const SearchArchitects(),
        '/post-project': (context) => const PostProject(),
        '/architect-dashboard': (context) => ArchitectDashboard(),
      },
    );
  }
}
